"""Initial migration.

Revision ID: 04011e73a571
Revises: 
Create Date: 2022-05-26 10:12:56.615921

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '04011e73a571'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('py_flora_pot', sa.Column('pot_name', sa.String(length=100), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('py_flora_pot', 'pot_name')
    # ### end Alembic commands ###
