"""Time stamp migration.

Revision ID: 38a33df76838
Revises: fb94c8f82aa2
Create Date: 2022-06-05 17:52:52.055061

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '38a33df76838'
down_revision = 'fb94c8f82aa2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sync', sa.Column('time_stamp', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('sync', 'time_stamp')
    # ### end Alembic commands ###
