"""Update

Revision ID: 45de9e3094c5
Revises: 9e0d083d3533
Create Date: 2022-05-31 08:15:05.128025

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '45de9e3094c5'
down_revision = '9e0d083d3533'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('flower', 'add_substrate')
    op.add_column('py_flora_pot', sa.Column('add_substrate', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('py_flora_pot', 'add_substrate')
    op.add_column('flower', sa.Column('add_substrate', sa.BOOLEAN(), nullable=True))
    # ### end Alembic commands ###
