"""Flower table change

Revision ID: 9e0d083d3533
Revises: 04011e73a571
Create Date: 2022-05-31 07:41:19.624087

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9e0d083d3533'
down_revision = '04011e73a571'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('flower', sa.Column('soil_humidity', sa.Float(), nullable=True))
    op.add_column('flower', sa.Column('soil_ph', sa.Float(), nullable=True))
    op.add_column('flower', sa.Column('soil_salinity', sa.Float(), nullable=True))
    op.drop_column('flower', 'flower_ph')
    op.drop_column('flower', 'flower_salinity')
    op.drop_column('flower', 'flower_humidity')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('flower', sa.Column('flower_humidity', sa.FLOAT(), nullable=True))
    op.add_column('flower', sa.Column('flower_salinity', sa.FLOAT(), nullable=True))
    op.add_column('flower', sa.Column('flower_ph', sa.FLOAT(), nullable=True))
    op.drop_column('flower', 'soil_salinity')
    op.drop_column('flower', 'soil_ph')
    op.drop_column('flower', 'soil_humidity')
    # ### end Alembic commands ###
